name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: ['8.0.2', '8.2.2', '8.6.5', '8.8.3', '8.10.3']
        cabal: ['1.8', '2.4', '3.2']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          # GHC 8.8+ doesn’t support Cabal below v3

          - ghc: 8.0.2
            cabal: 1.8
          - ghc: 8.0.2
            cabal: 2.4

          - ghc: 8.2.2
            cabal: 1.8
          - ghc: 8.2.2
            cabal: 2.4

          - ghc: 8.6.5
            cabal: 1.8
          - ghc: 8.6.5
            cabal: 2.4

    steps:
    - uses: actions/checkout@v3

    - name: Setup GHC ${{ matrix.ghc }} and Cabal ${{ matrix.cabal }} on ${{ matrix.os }}
      uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ matrix.os }}-build-${{ env.cache-name }}-
          ${{ matrix.os }}-build-
          ${{ matrix.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test all
